services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: quicktalk_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    env_file:
      - ../.env
    volumes:
      - ..:/app
    restart: always

  mongo:
    image: mongo:7
    container_name: quicktalk_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7
    container_name: quicktalk_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data: